export const caseStudyData = [
  {
    id: 1,
    imgUrl: "/images/casestudies/Google-Start-Up-Conclave-cs.png",
    alt: "Google Start Up Conclave",
    title: "Google Start Up Conclave",
    subTitle: "90 Attendees From 50 Unique Start ups",
    category: "B2B Lead Generation",
  },

  {
    id: 2,
    imgUrl: "/images/casestudies/Dell-16G-cs.png",
    alt: "Dell Technologies 16G",
    title: "Dell Technologies 16G",
    subTitle: "376 Unique Organizations",
    category: "B2B Lead Generation",
  },
  {
    id: 3,
    imgUrl: "/images/casestudies/Tata-Tele-cs.png",
    alt: "Tata Tele Business Services – The SME Growth Engine",
    title: "Tata Tele Business Services – The SME Growth Engine",
    subTitle: "353 Attendees from 341 Unique Organizations",
    category: "B2B Lead Generation",
  },

  {
    id: 4,
    imgUrl: "/images/casestudies/Elastic-On-cs.png",
    alt: "Audience Generation for ElasticON",
    title: "Audience Generation for ElasticON",
    subTitle: "2918 Registrations",
    category: "B2B Lead Generation",
  },
  {
    id: 5,
    imgUrl: "/images/casestudies/Thermofisher-cs.png",
    alt: "ThermoFisher",
    title: "ThermoFisher",
    subTitle: "17000 Sales Qualified Leads",
    category: "B2B Lead Generation",
  },

  {
    id: 6,
    imgUrl: "/images/casestudies/Adobe-Symposium-cs.png",
    alt: "Adobe Symposium",
    title: "Adobe Symposium",
    subTitle: "2400+ Registrations",
    category: "B2B Lead Generation",
  },

  {
    id: 7,
    imgUrl: "/images/casestudies/dell-x-intel-cs.png",
    alt: "Dell Technologies x Intel",
    title: "Dell Technologies x Intel",
    subTitle: "439 Unique Organizations",
    category: "B2B Lead Generation",
  },

  {
    id: 8,
    imgUrl: "/images/casestudies/AWS-Fintech-cs.png",
    alt: "HPC Innovation Challenge",
    title: "HPC Innovation Challenge",
    subTitle: "750+ Registrations | 400+ Attendees",
    category: "B2B Lead Generation",
  },

  {
    id: 9,
    imgUrl: "/images/casestudies/AWS-Sm-Bandh-cs.png",
    alt: "AWS SMBandh",
    title: "AWS SMBandh",
    subTitle: "3,150 Unique Organization",
    category: "B2B Lead Generation",
  },

  {
    id: 10,
    imgUrl: "/images/casestudies/freshworks-cs.png",
    alt: "FreshWorks",
    title: "FreshWorks",
    subTitle: "269 Meetings, 298 Leads",
    category: "B2B Lead Generation",
  },

  {
    id: 11,
    imgUrl: "/images/casestudies/Logitech-cs.png",
    alt: "Logitech VC Solutions",
    title: "Logitech VC Solutions",
    subTitle: "97 Leads Generated",
    category: "B2B Lead Generation",
  },
  {
    id: 12,
    imgUrl: "/images/casestudies/GitHub-cs.png",
    alt: "Github Galaxy 2024",
    title: "GitHub Galaxy 2024",
    subTitle: "Registrations from 323 Unique Organizations",
    category: "B2B Lead Generation",
  },
  {
    id: 13,
    imgUrl: "/images/casestudies/STT-Tele-Media-cs.png",
    alt: "Digital Marketing Services | STT Global Data Centre",
    title: "Digital Marketing Services | STT Global Data Centre",
    subTitle: "SEO. Social Media Marketing. PPC Campaigns.",
    category: "Digital Marketing",
  },
  {
    id: 14,
    imgUrl: "/images/casestudies/cambridge-cs.jpg",
    alt: "Social Media Management for Cambridge",
    title: "Social Media Management for Cambridge",
    subTitle: "Organic engagement up by 7x since inception",
    category: "Digital Marketing",
  },

  {
    id: 15,
    imgUrl: "/images/casestudies/Salesforce-cs.png",
    alt: "Salesforce Great India Sales and Marketing Summit, 2024",
    title: "Salesforce Great India Sales and Marketing Summit, 2024",
    subTitle: "2.7 Million+ Campaign Impressions",
    category: "Digital Marketing",
  },
  {
    id: 16,
    imgUrl: "/images/casestudies/vikram-tea-cs.png",
    alt: "E-Commerce Advertising for Vikram Tea",
    title: "E-Commerce Advertising for Vikram Tea",
    subTitle: "5.2 Million+ Campaign Reach | 7.9 Million+ Campaign Impressions",
    category: "Digital Marketing",
  },

  {
    id: 17,
    imgUrl: "/images/casestudies/Keysight-cs.png",
    alt: "Demand Generation for Keysight",
    title: "Demand Generation for Keysight",
    subTitle: "50K+ Reach. 2,200 Leads",
    category: "Digital Marketing",
  },
  {
    id: 18,
    imgUrl: "/images/casestudies/DS-cs.png",
    alt: "Audience & Lead Generation for Destiny Science",
    title: "Audience & Lead Generation for Destiny Science",
    subTitle: "83 Million+ Campaign Reach | 203 Million+ Campaign Impressions",
    category: "Digital Marketing",
  },
  {
    id: "em1",
    imgUrl: "/images/casestudies/cisco-cs.png",
    alt: "Cisco Partner Summit",
    title: "Cisco Partner Summit",
    subTitle: "500 Partners. Phuket, Thailand. ",
    category: "Experiential Marketing",
  },

  {
    id: "em2",
    imgUrl: "/images/casestudies/AWS-Public-summit-cs.png",
    alt: "AWS Public Sector Summit",
    title: "AWS Public Sector Summit",
    subTitle: "Public Sector Summit",
    category: "Experiential Marketing",
  },

  {
    id: "em3",
    imgUrl: "/images/casestudies/Dell-Emc-Connected-cs.png",
    alt: "Dell EMC Connected CIO Forum",
    title: "Dell EMC Connected CIO Forum",
    subTitle: "364 CIO. 3D Experiences.",
    category: "Experiential Marketing",
  },
  {
    id: "em4",
    imgUrl: "/images/casestudies/Cambridge-udaan-cs.png",
    alt: "UDAAN Cambridge Annual Conference",
    title: "UDAAN Cambridge Annual Conference",
    subTitle: "3 Day Conference. 500+ Employees. 04 Breakout Sessions. ",
    category: "Experiential Marketing",
  },

  {
    id: "em5",
    imgUrl: "/images/casestudies/dell-unplugged-cs.png",
    alt: "Dell Technologies Unplugged",
    title: "Dell Technologies Unplugged",
    subTitle: "300+ Attendees. 1Mn+ Impressions. 5000+ Reach",
    category: "Experiential Marketing",
  },
  {
    id: "em6",
    imgUrl: "/images/casestudies/ITC-cs.png",
    alt: "ITC Dark Fantasy Relaunch Project",
    title: "ITC Dark Fantasy Relaunch Project",
    subTitle: "08 Cities | 150+ attendees",
    category: "Experiential Marketing",
  },
];
